const en = {
  add:'Add',
  added:'added',
  addedBefore:'added before',
  AddToChatPage:'add to chat page',
  account:'Account',
  addGroup:'Add Group',
  enterName:'Enter Name',
  greet: 'Welcome',
  loginUser: 'Login User',
  languege: 'Languege',
  homePage: 'Home',
  online: 'Online',
  offline: 'Offline',
  notWorking: 'Not Working',
  persian: 'Persian',
  english: 'English',
  dark: 'Dark',
  light: 'Light',
  rose: 'Rose',
  toEdit: 'Click here to edit',
  logout: 'Logout',
  theme: 'Theme',
  contact: 'Contact',
  status: 'Status',
  setting: 'setting',
  fullName: 'FullName',
  userName: 'UserName',
  bio: 'bio',
  remove: 'Remove',
  gallery: 'From Gallery',
  takePhoto: 'Take Photo',
  message: 'Message...',
  password: 'Password',
  login: 'Login',
  forgetPassword: 'Forget Password',
  dontSendNotification: 'don`t send notification',
  notifcation: 'notification',
  deleteChat: 'delete chat',
  deleteContact: 'delete contact',
  messenger: 'Messanger',
  allChat: 'All',
  private: 'Private',
  group: 'Group',
  channel: 'Channel',
  newMessage: 'New Message',
  groupName: 'Group Name...',
  newGroup: 'New Group',
  yourInformationsAreFalse:'your informations are false!'
};

const fa = {
  add:'ایجاد',
  added:'اضافه شد',
  addedBefore:'قبلا اضافه شده',
  AddToChatPage:'به صفحه چت اضافه شد',
  account:'حساب',
  addGroup:'افزودن گروه',
  addMember:'افزودن عضو',
  enterName:'نام را وارد کنید',
  greet: 'خوش آمدید',
  loginUser: 'ورود کاربر',
  languege: 'زبان',
  homePage: 'خانه',
  online: 'آنلابن',
  offline: 'آفلاین',
  notWorking: 'دور از سیستم',
  persian: 'فارسی',
  english: 'انگلیسی',
  dark: 'تاریک',
  light: 'روشن',
  rose: 'رز',
  toEdit: 'برای ویرایش کلیک کنید',
  logout: 'خروج',
  theme: 'قالب',
  contact: 'مخاطبین',
  status: 'وضیعت',
  setting: 'تنظیمات',
  fullName: 'نام و نام خانوادگی',
  userName: 'نام کاربری',
  bio: 'درباره من',
  remove: 'حذف',
  gallery: 'از گالری',
  takePhoto: 'گرفتن عکس',
  choosePhoto:'انتخاب عکس',
  message: 'پیام...',
  password: 'رمزعبور',
  login: 'ورود',
  leaveTheGroup:'رفتن از گروه',
  forgetPassword: 'فراموشی رمز عبور',
  notification: 'اعلان رخداد',
  deleteChat: 'حذف مکالمات',
  deleteContact: 'حذف مخاطب',
  messenger: 'پیامرسان',
  members:'اعضا',
  allChat: 'همه',
  private: 'خصوصی',
  group: 'گروه',
  channel: 'کانال',
  channelName:'نام کانال',
  newMessage: 'پیام جدید',
  GroupName: 'نام گروه',
  newGroup: 'گروه جدید',
  yourInformationsAreFalse:'اطلاعات واردشده نادرست است!'
};

const translate = {
  en,
  fa,
};

export default translate;
